name: Auto-update Jailbreak Repo

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg bzip2 gzip xz-utils zstd apt-utils

      - name: Generate Packages
        run: |
          cd repo
          dpkg-scanpackages -m debs > Packages

      - name: Compress Packages
        run: |
          cd repo
          bzip2 -fk Packages
          gzip -fk Packages
          xz -fk Packages
          zstd -f Packages -o Packages.zst

      - name: Generate Release
        run: |
          cd repo
          apt-ftparchive -c Release.conf release . > Release

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add repo/Packages repo/Packages.bz2 repo/Packages.gz repo/Packages.xz repo/Packages.zst repo/Release
          git commit -m 'Update Packages, compressed variants, and Release with hashes' || echo "No changes to commit"
          git push