name: Auto-update Jailbreak Repo

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg

      - name: Generate Packages
        run: |
          cd repo
          dpkg-scanpackages -m debs > Packages

      - name: Compress Packages
        run: bzip2 -fk ./repo/Packages

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -f repo/Packages repo/Packages.bz2
          git commit -m 'Update Packages' || echo "No changes to commit"
          git push
